package wrappers.example.footer

import js.import.importAsync
import wrappers.example.lazy.lazyComponent

// TODO: must be generated by plugin
internal val LazyFooter = lazyComponent("Footer") {
    importAsync("./footer.export.mjs")
}
