package karakum.csstype

internal val SVG_TYPES = setOf(
    "AlignmentBaseline",
    "BaselineShift",
    "Clip",
    "ClipRule",
    "ColorInterpolation",
    "ColorRendering",
    "DominantBaseline",
    "Fill",
    "FillOpacity",
    "FillRule",
    "FloodColor",
    "FloodOpacity",
    "GlyphOrientationVertical",
    "LightingColor",
    "Marker",
    "MarkerEnd",
    "MarkerMid",
    "MarkerStart",
    "ShapeRendering",
    "StopColor",
    "StopOpacity",
    "Stroke",
    "StrokeDasharray",
    "StrokeDashoffset",
    "StrokeLinecap",
    "StrokeLinejoin",
    "StrokeMiterlimit",
    "StrokeOpacity",
    "StrokeWidth",
    "TextAnchor",
    "VectorEffect",

    "Viewport",
)
