package dom.svg

typealias SVGElement = org.w3c.dom.svg.SVGElement

typealias SVGAElement = org.w3c.dom.svg.SVGAElement
typealias SVGAnimateElement = org.w3c.dom.svg.SVGElement // SVGAnimateElement
typealias SVGAnimateMotionElement = org.w3c.dom.svg.SVGElement // SVGAnimateMotionElement
typealias SVGAnimateTransformElement = org.w3c.dom.svg.SVGElement // SVGAnimateTransformElement
typealias SVGCircleElement = org.w3c.dom.svg.SVGCircleElement
typealias SVGClipPathElement = org.w3c.css.masking.SVGClipPathElement
typealias SVGDefsElement = org.w3c.dom.svg.SVGDefsElement
typealias SVGDescElement = org.w3c.dom.svg.SVGDescElement
typealias SVGEllipseElement = org.w3c.dom.svg.SVGEllipseElement
typealias SVGFEBlendElement = org.w3c.dom.svg.SVGElement // SVGFEBlendElement
typealias SVGFEColorMatrixElement = org.w3c.dom.svg.SVGElement // SVGFEColorMatrixElement
typealias SVGFEComponentTransferElement = org.w3c.dom.svg.SVGElement // SVGFEComponentTransferElement
typealias SVGFECompositeElement = org.w3c.dom.svg.SVGElement // SVGFECompositeElement
typealias SVGFEConvolveMatrixElement = org.w3c.dom.svg.SVGElement // SVGFEConvolveMatrixElement
typealias SVGFEDiffuseLightingElement = org.w3c.dom.svg.SVGElement // SVGFEDiffuseLightingElement
typealias SVGFEDisplacementMapElement = org.w3c.dom.svg.SVGElement // SVGFEDisplacementMapElement
typealias SVGFEDistantLightElement = org.w3c.dom.svg.SVGElement // SVGFEDistantLightElement
typealias SVGFEDropShadowElement = org.w3c.dom.svg.SVGElement // SVGFEDropShadowElement
typealias SVGFEFloodElement = org.w3c.dom.svg.SVGElement // SVGFEFloodElement
typealias SVGFEFuncAElement = org.w3c.dom.svg.SVGElement // SVGFEFuncAElement
typealias SVGFEFuncBElement = org.w3c.dom.svg.SVGElement // SVGFEFuncBElement
typealias SVGFEFuncGElement = org.w3c.dom.svg.SVGElement // SVGFEFuncGElement
typealias SVGFEFuncRElement = org.w3c.dom.svg.SVGElement // SVGFEFuncRElement
typealias SVGFEGaussianBlurElement = org.w3c.dom.svg.SVGElement // SVGFEGaussianBlurElement
typealias SVGFEImageElement = org.w3c.dom.svg.SVGElement // SVGFEImageElement
typealias SVGFEMergeElement = org.w3c.dom.svg.SVGElement // SVGFEMergeElement
typealias SVGFEMergeNodeElement = org.w3c.dom.svg.SVGElement // SVGFEMergeNodeElement
typealias SVGFEMorphologyElement = org.w3c.dom.svg.SVGElement // SVGFEMorphologyElement
typealias SVGFEOffsetElement = org.w3c.dom.svg.SVGElement // SVGFEOffsetElement
typealias SVGFEPointLightElement = org.w3c.dom.svg.SVGElement // SVGFEPointLightElement
typealias SVGFESpecularLightingElement = org.w3c.dom.svg.SVGElement // SVGFESpecularLightingElement
typealias SVGFESpotLightElement = org.w3c.dom.svg.SVGElement // SVGFESpotLightElement
typealias SVGFETileElement = org.w3c.dom.svg.SVGElement // SVGFETileElement
typealias SVGFETurbulenceElement = org.w3c.dom.svg.SVGElement // SVGFETurbulenceElement
typealias SVGFilterElement = org.w3c.dom.svg.SVGElement // SVGFilterElement
typealias SVGForeignObjectElement = org.w3c.dom.svg.SVGForeignObjectElement
typealias SVGGElement = org.w3c.dom.svg.SVGGElement
typealias SVGImageElement = org.w3c.dom.svg.SVGImageElement
typealias SVGLineElement = org.w3c.dom.svg.SVGLineElement
typealias SVGLinearGradientElement = org.w3c.dom.svg.SVGLinearGradientElement
typealias SVGMarkerElement = org.w3c.dom.svg.SVGMarkerElement
typealias SVGMaskElement = org.w3c.css.masking.SVGMaskElement
typealias SVGMetadataElement = org.w3c.dom.svg.SVGMetadataElement
typealias SVGMPathElement = org.w3c.dom.svg.SVGElement // SVGMPathElement
typealias SVGPathElement = org.w3c.dom.svg.SVGPathElement
typealias SVGPatternElement = org.w3c.dom.svg.SVGPatternElement
typealias SVGPolygonElement = org.w3c.dom.svg.SVGPolygonElement
typealias SVGPolylineElement = org.w3c.dom.svg.SVGPolylineElement
typealias SVGRadialGradientElement = org.w3c.dom.svg.SVGRadialGradientElement
typealias SVGRectElement = org.w3c.dom.svg.SVGRectElement
typealias SVGScriptElement = org.w3c.dom.svg.SVGScriptElement
typealias SVGSetElement = org.w3c.dom.svg.SVGElement // SVGSetElement
typealias SVGStopElement = org.w3c.dom.svg.SVGStopElement
typealias SVGStyleElement = org.w3c.dom.svg.SVGStyleElement
typealias SVGSVGElement = org.w3c.dom.svg.SVGSVGElement
typealias SVGSwitchElement = org.w3c.dom.svg.SVGSwitchElement
typealias SVGSymbolElement = org.w3c.dom.svg.SVGSymbolElement
typealias SVGTextElement = org.w3c.dom.svg.SVGTextElement
typealias SVGTextPathElement = org.w3c.dom.svg.SVGTextPathElement
typealias SVGTitleElement = org.w3c.dom.svg.SVGTitleElement
typealias SVGTSpanElement = org.w3c.dom.svg.SVGTSpanElement
typealias SVGUseElement = org.w3c.dom.svg.SVGUseElement
typealias SVGViewElement = org.w3c.dom.svg.SVGViewElement
