@file:JsModule("pako")

package pako

import js.buffer.ArrayBuffer
import js.typedarrays.Uint8Array

/**
 * Generic JS-style wrapper for zlib calls. If you don't need
 * streaming behaviour - use more simple functions: [deflate],
 * [deflateRaw] and [gzip].
 */
open external class Deflate(
    options: DeflateOptions = definedExternally,
) {
    /**
     * Compressed result, generated by default [onData]
     * and [onEnd] handlers. Filled after you push last chunk
     * (call [push] with [Flush.Z_FINISH] param).
     */
    val result: Uint8Array<ArrayBuffer>?

    /**
     * Error code after deflate finished. [ReturnCode.Z_OK] on success.
     * You will not need it in real life, because deflate errors
     * are possible only on wrong options or bad [onData] / [onEnd]
     * custom handlers.
     */
    val err: ReturnCode?

    /**
     * Error message, if [err] != ReturnCode.Z_OK
     */
    val msg: String?

    /**
     * By default, stores data blocks in `chunks[]` property and glue
     * those in `onEnd`. Override this handler, if you need another behaviour.
     */
    open fun onData(
        chunk: Uint8Array<ArrayBuffer>,
    )

    /**
     * Called either after you tell inflate that the input stream is
     * complete (Z_FINISH). By default - join collected chunks,
     * free memory and fill `results` / `err` properties.
     */
    open fun onEnd(
        status: ReturnCode,
    )

    /**
     * Sends input data to deflate pipe, generating [onData] calls with
     * new compressed chunks. Returns `true` on success. The last data block must
     * have `flush_mode` [Flush.Z_FINISH]. That will flush internal pending
     * buffers and call [onEnd].
     *
     * On fail call [onEnd] with error code and return false.
     */
    fun push(
        data: Uint8Array<*>,
        flush: Flush = definedExternally,
    ): Boolean

    /**
     * Sends input data to deflate pipe, generating [onData] calls with
     * new compressed chunks. Returns `true` on success. The last data block must
     * have `flush_mode` [Flush.Z_FINISH]. That will flush internal pending
     * buffers and call [onEnd].
     *
     * On fail call [onEnd] with error code and return false.
     */
    fun push(
        data: ArrayBuffer,
        flush: Flush = definedExternally,
    ): Boolean

    /**
     * Sends input data to deflate pipe, generating [onData] calls with
     * new compressed chunks. Returns `true` on success. The last data block must
     * have `flush_mode` [Flush.Z_FINISH]. That will flush internal pending
     * buffers and call [onEnd].
     *
     * On fail call [onEnd] with error code and return false.
     */
    fun push(
        data: String,
        flush: Flush = definedExternally,
    ): Boolean
}
