@file:JsModule("pako")

package pako

import js.buffer.ArrayBuffer
import js.typedarrays.Uint8Array

/**
 * Generic JS-style wrapper for zlib calls. If you don't need
 * streaming behaviour - use more simple functions: [inflate]
 * and [inflateRaw].
 */
open external class Inflate(
    options: InflateOptions = definedExternally,
) {
    /**
     * Uncompressed result, generated by default [onData]
     * and [onEnd] handlers. Filled after you push last chunk
     * (call [push] with [Flush.Z_FINISH] param).
     */
    val result: Uint8Array<ArrayBuffer>?

    /**
     * Error code after inflate finished. [ReturnCode.Z_OK] on success.
     * Should be checked if broken data possible.
     */
    val err: ReturnCode?

    /**
     * Error message, if [err] != ReturnCode.Z_OK
     */
    val msg: String?

    /**
     * By default, stores data blocks in `chunks[]` property and glue
     * those in `onEnd`. Override this handler, if you need another behaviour.
     */
    open fun onData(
        chunk: Uint8Array<ArrayBuffer>,
    )

    /**
     * Called either after you tell inflate that the input stream is
     * complete [Flush.Z_FINISH]. By default - join collected chunks,
     * free memory and fill `results` / `err` properties.
     */
    open fun onEnd(
        status: ReturnCode,
    )

    /**
     * Sends input data to inflate pipe, generating [onData] calls with
     * new output chunks. Returns `true` on success. If end of stream detected,
     * [onEnd] will be called.
     *
     * `flush_mode` is not needed for normal operation, because end of stream
     * detected automatically. You may try to use it for advanced things, but
     * this functionality was not tested.
     *
     * On fail call [onEnd] with error code and return false.
     */
    fun push(
        data: Uint8Array<*>,
        flush: Flush = definedExternally,
    ): Boolean

    /**
     * Sends input data to inflate pipe, generating [onData] calls with
     * new output chunks. Returns `true` on success. If end of stream detected,
     * [onEnd] will be called.
     *
     * `flush_mode` is not needed for normal operation, because end of stream
     * detected automatically. You may try to use it for advanced things, but
     * this functionality was not tested.
     *
     * On fail call [onEnd] with error code and return false.
     */
    fun push(
        data: ArrayBuffer,
        flush: Flush = definedExternally,
    ): Boolean

    /**
     * Sends input data to inflate pipe, generating [onData] calls with
     * new output chunks. Returns `true` on success. If end of stream detected,
     * [onEnd] will be called.
     *
     * `flush_mode` is not needed for normal operation, because end of stream
     * detected automatically. You may try to use it for advanced things, but
     * this functionality was not tested.
     *
     * On fail call [onEnd] with error code and return false.
     */
    fun push(
        data: String,
        flush: Flush = definedExternally,
    ): Boolean
}
