// Generated by Karakum - do not modify it manually!

@file:JsModule("semver/functions/valid")

package semver

/* import semver = require("../index"); */

/* import SemVer = require("../classes/semver"); */

/**
 * Return the parsed version as a string, or null if it's not valid.
 */
external fun valid(version: String?): String?

/**
 * Return the parsed version as a string, or null if it's not valid.
 */
external fun valid(version: String?, optionsOrLoose: Boolean = definedExternally): String?

/**
 * Return the parsed version as a string, or null if it's not valid.
 */
external fun valid(version: String?, optionsOrLoose: semver.Options = definedExternally): String?

/**
 * Return the parsed version as a string, or null if it's not valid.
 */
external fun valid(version: SemVer?): String?

/**
 * Return the parsed version as a string, or null if it's not valid.
 */
external fun valid(version: SemVer?, optionsOrLoose: Boolean = definedExternally): String?

/**
 * Return the parsed version as a string, or null if it's not valid.
 */
external fun valid(version: SemVer?, optionsOrLoose: semver.Options = definedExternally): String?

/* export = valid; */
