import ts from "typescript"

export default (node) => {
    if (
        ts.isMethodDeclaration(node)
        && ts.isIdentifier(node.name)
        && (
            (
                (
                    node.name.text === "blur"
                    || node.name.text === "center"
                    || node.name.text === "close"
                    || node.name.text === "closeFilePreview"
                    || node.name.text === "destroy"
                    || node.name.text === "flashFrame"
                    || node.name.text === "focus"
                    || node.name.text === "getBackgroundColor"
                    || node.name.text === "getBounds"
                    || node.name.text === "getChildWindows"
                    || node.name.text === "getContentBounds"
                    || node.name.text === "getContentSize"
                    || node.name.text === "getMaximumSize"
                    || node.name.text === "getMediaSourceId"
                    || node.name.text === "getMinimumSize"
                    || node.name.text === "getNativeWindowHandle"
                    || node.name.text === "getNormalBounds"
                    || node.name.text === "getOpacity"
                    || node.name.text === "getParentWindow"
                    || node.name.text === "getPosition"
                    || node.name.text === "getRepresentedFilename"
                    || node.name.text === "getSize"
                    || node.name.text === "getTitle"
                    || node.name.text === "getWindowButtonPosition"
                    || node.name.text === "hasShadow"
                    || node.name.text === "hide"
                    || node.name.text === "hookWindowMessage"
                    || node.name.text === "invalidateShadow"
                    || node.name.text === "isAlwaysOnTop"
                    || node.name.text === "isClosable"
                    || node.name.text === "isDestroyed"
                    || node.name.text === "isDocumentEdited"
                    || node.name.text === "isEnabled"
                    || node.name.text === "isFocusable"
                    || node.name.text === "isFocused"
                    || node.name.text === "isFullScreen"
                    || node.name.text === "isFullScreenable"
                    || node.name.text === "isHiddenInMissionControl"
                    || node.name.text === "isKiosk"
                    || node.name.text === "isMaximizable"
                    || node.name.text === "isMaximized"
                    || node.name.text === "isMenuBarAutoHide"
                    || node.name.text === "isMenuBarVisible"
                    || node.name.text === "isMinimizable"
                    || node.name.text === "isMinimized"
                    || node.name.text === "isModal"
                    || node.name.text === "isMovable"
                    || node.name.text === "isNormal"
                    || node.name.text === "isResizable"
                    || node.name.text === "isSimpleFullScreen"
                    || node.name.text === "isTabletMode"
                    || node.name.text === "isVisible"
                    || node.name.text === "isVisibleOnAllWorkspaces"
                    || node.name.text === "isWindowMessageHooked"
                    || node.name.text === "maximize"
                    || node.name.text === "mergeAllWindows"
                    || node.name.text === "minimize"
                    || node.name.text === "moveAbove"
                    || node.name.text === "moveTabToNewWindow"
                    || node.name.text === "moveTop"
                    || node.name.text === "previewFile"
                    || node.name.text === "removeMenu"
                    || node.name.text === "restore"
                    || node.name.text === "selectNextTab"
                    || node.name.text === "selectPreviousTab"
                    || node.name.text === "setAppDetails"
                    || node.name.text === "setAspectRatio"
                    || node.name.text === "setAutoHideCursor"
                    || node.name.text === "setAutoHideMenuBar"
                    || node.name.text === "setBackgroundColor"
                    || node.name.text === "setBounds"
                    || node.name.text === "setClosable"
                    || node.name.text === "setContentBounds"
                    || node.name.text === "setContentProtection"
                    || node.name.text === "setContentSize"
                    || node.name.text === "setDocumentEdited"
                    || node.name.text === "setEnabled"
                    || node.name.text === "setFocusable"
                    || node.name.text === "setFullScreen"
                    || node.name.text === "setFullScreenable"
                    || node.name.text === "setHasShadow"
                    || node.name.text === "setHiddenInMissionControl"
                    || node.name.text === "setIcon"
                    || node.name.text === "setIcon"
                    || node.name.text === "setIgnoreMouseEvents"
                    || node.name.text === "setKiosk"
                    || node.name.text === "setMaximizable"
                    || node.name.text === "setMaximumSize"
                    || node.name.text === "setMenu"
                    || node.name.text === "setMenuBarVisibility"
                    || node.name.text === "setMinimizable"
                    || node.name.text === "setMinimumSize"
                    || node.name.text === "setMovable"
                    || node.name.text === "setOpacity"
                    || node.name.text === "setOverlayIcon"
                    || node.name.text === "setPosition"
                    || node.name.text === "setProgressBar"
                    || node.name.text === "setRepresentedFilename"
                    || node.name.text === "setResizable"
                    || node.name.text === "setShape"
                    || node.name.text === "setSheetOffset"
                    || node.name.text === "setSimpleFullScreen"
                    || node.name.text === "setSize"
                    || node.name.text === "setSkipTaskbar"
                    || node.name.text === "setThumbarButtons"
                    || node.name.text === "setThumbnailClip"
                    || node.name.text === "setThumbnailToolTip"
                    || node.name.text === "setTitle"
                    || node.name.text === "setTitleBarOverlay"
                    || node.name.text === "setTouchBar"
                    || node.name.text === "setVisibleOnAllWorkspaces"
                    || node.name.text === "setWindowButtonPosition"
                    || node.name.text === "setWindowButtonVisibility"
                    || node.name.text === "show"
                    || node.name.text === "showAllTabs"
                    || node.name.text === "showInactive"
                    || node.name.text === "toggleTabBar"
                    || node.name.text === "unhookAllWindowMessages"
                    || node.name.text === "unhookWindowMessage"
                    || node.name.text === "unmaximize"
                )
                && node.parent
                && node.parent.name?.text === "BaseWindow"
            )
        )
    ) {
        return "open"
    }

    if (
        ts.isMethodDeclaration(node)
        && ts.isIdentifier(node.name)
        && (
            (
                (
                    node.name.text === "blur"
                    || node.name.text === "center"
                    || node.name.text === "close"
                    || node.name.text === "closeFilePreview"
                    || node.name.text === "destroy"
                    || node.name.text === "flashFrame"
                    || node.name.text === "focus"
                    || node.name.text === "getBackgroundColor"
                    || node.name.text === "getBounds"
                    || node.name.text === "getChildWindows"
                    || node.name.text === "getContentBounds"
                    || node.name.text === "getContentSize"
                    || node.name.text === "getMaximumSize"
                    || node.name.text === "getMediaSourceId"
                    || node.name.text === "getMinimumSize"
                    || node.name.text === "getNativeWindowHandle"
                    || node.name.text === "getNormalBounds"
                    || node.name.text === "getOpacity"
                    || node.name.text === "getParentWindow"
                    || node.name.text === "getPosition"
                    || node.name.text === "getRepresentedFilename"
                    || node.name.text === "getSize"
                    || node.name.text === "getTitle"
                    || node.name.text === "getWindowButtonPosition"
                    || node.name.text === "hasShadow"
                    || node.name.text === "hide"
                    || node.name.text === "hookWindowMessage"
                    || node.name.text === "invalidateShadow"
                    || node.name.text === "isAlwaysOnTop"
                    || node.name.text === "isClosable"
                    || node.name.text === "isDestroyed"
                    || node.name.text === "isDocumentEdited"
                    || node.name.text === "isEnabled"
                    || node.name.text === "isFocusable"
                    || node.name.text === "isFocused"
                    || node.name.text === "isFullScreen"
                    || node.name.text === "isFullScreenable"
                    || node.name.text === "isHiddenInMissionControl"
                    || node.name.text === "isKiosk"
                    || node.name.text === "isMaximizable"
                    || node.name.text === "isMaximized"
                    || node.name.text === "isMenuBarAutoHide"
                    || node.name.text === "isMenuBarVisible"
                    || node.name.text === "isMinimizable"
                    || node.name.text === "isMinimized"
                    || node.name.text === "isModal"
                    || node.name.text === "isMovable"
                    || node.name.text === "isNormal"
                    || node.name.text === "isResizable"
                    || node.name.text === "isSimpleFullScreen"
                    || node.name.text === "isTabletMode"
                    || node.name.text === "isVisible"
                    || node.name.text === "isVisibleOnAllWorkspaces"
                    || node.name.text === "isWindowMessageHooked"
                    || node.name.text === "maximize"
                    || node.name.text === "mergeAllWindows"
                    || node.name.text === "minimize"
                    || node.name.text === "moveAbove"
                    || node.name.text === "moveTabToNewWindow"
                    || node.name.text === "moveTop"
                    || node.name.text === "previewFile"
                    || node.name.text === "removeMenu"
                    || node.name.text === "restore"
                    || node.name.text === "selectNextTab"
                    || node.name.text === "selectPreviousTab"
                    || node.name.text === "setAppDetails"
                    || node.name.text === "setAspectRatio"
                    || node.name.text === "setAutoHideCursor"
                    || node.name.text === "setAutoHideMenuBar"
                    || node.name.text === "setBackgroundColor"
                    || node.name.text === "setBounds"
                    || node.name.text === "setClosable"
                    || node.name.text === "setContentBounds"
                    || node.name.text === "setContentProtection"
                    || node.name.text === "setContentSize"
                    || node.name.text === "setDocumentEdited"
                    || node.name.text === "setEnabled"
                    || node.name.text === "setFocusable"
                    || node.name.text === "setFullScreen"
                    || node.name.text === "setFullScreenable"
                    || node.name.text === "setHasShadow"
                    || node.name.text === "setHiddenInMissionControl"
                    || node.name.text === "setIcon"
                    || node.name.text === "setIcon"
                    || node.name.text === "setIgnoreMouseEvents"
                    || node.name.text === "setKiosk"
                    || node.name.text === "setMaximizable"
                    || node.name.text === "setMaximumSize"
                    || node.name.text === "setMenu"
                    || node.name.text === "setMenuBarVisibility"
                    || node.name.text === "setMinimizable"
                    || node.name.text === "setMinimumSize"
                    || node.name.text === "setMovable"
                    || node.name.text === "setOpacity"
                    || node.name.text === "setOverlayIcon"
                    || node.name.text === "setPosition"
                    || node.name.text === "setProgressBar"
                    || node.name.text === "setRepresentedFilename"
                    || node.name.text === "setResizable"
                    || node.name.text === "setShape"
                    || node.name.text === "setSheetOffset"
                    || node.name.text === "setSimpleFullScreen"
                    || node.name.text === "setSize"
                    || node.name.text === "setSkipTaskbar"
                    || node.name.text === "setThumbarButtons"
                    || node.name.text === "setThumbnailClip"
                    || node.name.text === "setThumbnailToolTip"
                    || node.name.text === "setTitle"
                    || node.name.text === "setTitleBarOverlay"
                    || node.name.text === "setTouchBar"
                    || node.name.text === "setVisibleOnAllWorkspaces"
                    || node.name.text === "setWindowButtonPosition"
                    || node.name.text === "setWindowButtonVisibility"
                    || node.name.text === "show"
                    || node.name.text === "showAllTabs"
                    || node.name.text === "showInactive"
                    || node.name.text === "toggleTabBar"
                    || node.name.text === "unhookAllWindowMessages"
                    || node.name.text === "unhookWindowMessage"
                    || node.name.text === "unmaximize"
                )
                && node.parent
                && node.parent.name?.text === "BrowserWindow"
            )
        )
    ) {
        return "override"
    }

    return null
}
