name: CI-K2.1

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Build
        run: |
          ./gradlew build -Pkotlin.version=2.1.0-RC -Pseskar.version=3.49.1

  build-examples:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Build Examples
        run: |
          ./gradlew publishToMavenLocal -Pkotlin.version=2.1.0-RC -Pseskar.version=3.49.1
          cd examples/
          ./gradlew build -Pkotlin.version=2.1.0-RC  -Pseskar.version=3.49.1
